# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [Visa, Nogo]
patreon: # Replace with a single Patreon username tor.onion
open_collective: # Replace with a single Open Collective username opensea.io
ko_fi: # Replace with a single Ko-fi username mouse3687
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username gates
issuehunt: # Replace with a single IssueHunt username tor.onion
otechie: # Replace with a single Otechie username iab
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://torproject.org','https://cdc.gov','https://wikimedia.org','https://apple.com', 'https://hunterz.io']
